import ctypes, sys
cg = ctypes.CDLL('/System/Library/Frameworks/CoreGraphics.framework/CoreGraphics')
cf = ctypes.CDLL('/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation')
def setup(lib,nm,rt,at): f=getattr(lib,nm); f.restype=rt; f.argtypes=at; return f
setup(cg,"CGMainDisplayID",ctypes.c_uint32,[])
setup(cg,"CGDisplayCreateImage",ctypes.c_void_p,[ctypes.c_uint32])
setup(cg,"CGImageGetWidth",ctypes.c_size_t,[ctypes.c_void_p])
setup(cg,"CGImageGetHeight",ctypes.c_size_t,[ctypes.c_void_p])
setup(cg,"CGImageGetDataProvider",ctypes.c_void_p,[ctypes.c_void_p])
setup(cg,"CGDataProviderCopyData",ctypes.c_void_p,[ctypes.c_void_p])
setup(cf,"CFDataGetLength",ctypes.c_long,[ctypes.c_void_p])
setup(cf,"CFDataGetBytePtr",ctypes.c_void_p,[ctypes.c_void_p])
did = cg.CGMainDisplayID()
img = cg.CGDisplayCreateImage(did)
print("CGDisplayCreateImage -> %s" % (hex(img) if img else "NULL"), flush=True)
if not img: sys.exit(2)
w=cg.CGImageGetWidth(img); h=cg.CGImageGetHeight(img)
dp=cg.CGImageGetDataProvider(img); data=cg.CGDataProviderCopyData(dp)
n=cf.CFDataGetLength(data); p=cf.CFDataGetBytePtr(data)
buf=(ctypes.c_ubyte*n).from_address(p)
nz=sum(1 for i in range(0, n, 37) if buf[i]>8)
print("CGImage w=%d h=%d datalen=%d nonblack(sampled)=%d" % (w,h,n,nz))
