import ctypes, sys
cg = ctypes.CDLL('/System/Library/Frameworks/CoreGraphics.framework/CoreGraphics')
cf = ctypes.CDLL('/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation')
def S(lib,nm,rt,at): f=getattr(lib,nm); f.restype=rt; f.argtypes=at; return f
S(cg,"CGMainDisplayID",ctypes.c_uint32,[])
S(cg,"CGDisplayBaseAddress",ctypes.c_void_p,[ctypes.c_uint32])
S(cg,"CGDisplayBytesPerRow",ctypes.c_size_t,[ctypes.c_uint32])
S(cg,"CGDisplayCreateImage",ctypes.c_void_p,[ctypes.c_uint32])
S(cg,"CGImageGetWidth",ctypes.c_size_t,[ctypes.c_void_p])
S(cg,"CGImageGetHeight",ctypes.c_size_t,[ctypes.c_void_p])
S(cg,"CGImageGetDataProvider",ctypes.c_void_p,[ctypes.c_void_p])
S(cg,"CGDataProviderCopyData",ctypes.c_void_p,[ctypes.c_void_p])
S(cf,"CFDataGetLength",ctypes.c_long,[ctypes.c_void_p])
S(cf,"CFDataGetBytePtr",ctypes.c_void_p,[ctypes.c_void_p])
did=cg.CGMainDisplayID(); base=cg.CGDisplayBaseAddress(did); bpr=cg.CGDisplayBytesPerRow(did)
print("base=%s bpr=%d"%(hex(base) if base else "NULL",bpr),flush=True)
# fill top 600 rows white in this process's base buffer
for y in range(600): ctypes.memset(base+y*bpr,0xFF,bpr)
img=cg.CGDisplayCreateImage(did)
print("img=%s"%(hex(img) if img else "NULL"),flush=True)
if not img: sys.exit(2)
w=cg.CGImageGetWidth(img); h=cg.CGImageGetHeight(img)
dp=cg.CGImageGetDataProvider(img); data=cg.CGDataProviderCopyData(dp)
n=cf.CFDataGetLength(data); p=cf.CFDataGetBytePtr(data)
buf=(ctypes.c_ubyte*n).from_address(p)
nz=sum(1 for i in range(0,n,37) if buf[i]>8)
print("after base-fill: CGImage %dx%d nonblack(sampled)=%d"%(w,h,nz))
